
title: My Blog
url: 'http://putrinadyafazri.github.io'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Putri Nadya Fazri  ## put your name
title: 'Student at UIN SUSKA RIAU'  ## your title
location: INDONESIA


## Social Profiles
#facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com/nadyappp  ## your twitter account url
linkedin: http://www.linkedin.com/putrinadyafazri  ## your linkedin account url
instagram: http://www.instagram.com/putrinadfa  ## you dribbble account url
#foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
